apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nixl8gbtj-go
  janus-idp.io/tekton: nixl8gbtj-go
  backstage.io/kubernetes-id: nixl8gbtj-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nixl8gbtj-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
