apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nixl8gbtj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nixl8gbtj-go 
  name: nixl8gbtj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nixl8gbtj-go 
